### ISSUE TITLE
qiime2-2021.2 installation error

### ISSUE THREAD

**Issue by jwdebelius** [bokulich-lab/RESCRIPt#94]
Hello lovely RESCRIPt team!

Because I'm trying to be cutting edge (and I have a plugin I want to update that relies on RESCRIPt 😄), I was trying to update t qiime2-2021.2.

When I go to refresh the cache, I get the following error in  setting up the plugin, I think related to a disjoint between RESCRIPt's feature classifier and the core q2-feature-classifier functionality.

```
Traceback (most recent call last):
  File "/Users/jusdeb/miniconda3/envs/test-env/bin/qiime", line 11, in <module>
    sys.exit(qiime())
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/builtin/dev.py", line 31, in refresh_cache
    import q2cli.core.cache
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/core/cache.py", line 406, in <module>
    CACHE = DeploymentCache()
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/core/cache.py", line 61, in __init__
    self._state = self._get_cached_state(refresh=refresh)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/core/cache.py", line 107, in _get_cached_state
    self._cache_current_state(current_requirements)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/core/cache.py", line 200, in _cache_current_state
    state = self._get_current_state()
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/q2cli/core/cache.py", line 238, in _get_current_state
    plugin_manager = qiime2.sdk.PluginManager()
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 54, in __new__
    self._init(add_plugins=add_plugins)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/sdk/plugin_manager.py", line 81, in _init
    plugin = entry_point.load()
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2472, in load
    return self.resolve()
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2478, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/rescript/plugin_setup.py", line 144, in <module>
    citations=[citations['bokulich2018optimizing']]
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/plugin/plugin.py", line 301, in register_function
    deprecated, examples)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/sdk/action.py", line 526, in _init
    output_descriptions)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/core/type/signature.py", line 118, in __init__
    self._assert_valid_parameters(parameters)
  File "/Users/jusdeb/miniconda3/envs/test-env/lib/python3.6/site-packages/qiime2/core/type/signature.py", line 270, in _assert_valid_parameters
    % (param_name, spec.qiime_type))
TypeError: Default value for parameter 'reads_per_batch' is not of semantic QIIME type Int % Range(1, None) | Str % Choices('auto') or `None`.
```

**Comment by nbokulich** [comment]
thanks @jwdebelius ! Looks like the latest release made breaking changes, but it will be easy to fix, expect more soon...

**Comment by misialq** [comment]
Hey @jwdebelius! All should work now 🛠️
